# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField()),
                ('description', models.CharField(max_length=2000)),
                ('image_path', models.CharField(max_length=255)),
                ('status', models.TextField()),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('order_value', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HNContributorRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('language_id', models.IntegerField(blank=True, null=True)),
                ('topic_cat_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contributor_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HNLanguage',
            fields=[
                ('lan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField()),
                ('lang_name', models.CharField(max_length=255)),
                ('status', models.TextField()),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('topic_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_value', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic_category',
                'managed': False,
            },
        ),
    ]
