# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_auto_20200514_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynccronmail',
            name='job_id',
            field=models.TextField(null=True),
        ),
    ]
