# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_asynccronmail_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynccronmail',
            name='sender',
            field=models.EmailField(default='no-reply@spoken-tutorial.org', max_length=254),
        ),
    ]
