# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-02-08 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_auto_20260127_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cron', '0005_asynccronmail_ers_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.IntegerField(choices=[(1, 'TEST'), (2, 'TRAINING')])),
                ('status', models.IntegerField(choices=[(0, 'QUEUED'), (1, 'RUNNING'), (2, 'DONE'), (3, 'FAILED')], default=0)),
                ('rq_job_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_path', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Test')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.TrainingRequest')),
            ],
        ),
    ]
