# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20190306_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccenter',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.City'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.District'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='institute_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.InstituteCategory'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='institution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.InstituteType'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Location'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.University'),
        ),
        migrations.AlterField(
            model_name='academiccenter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountexecutive',
            name='academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='accountexecutive',
            name='appoved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accountexecutive_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountexecutive',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accountexecutive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='coursemap',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.LabCourse'),
        ),
        migrations.AlterField(
            model_name='coursemap',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='eventsnotification',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='eventsnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fossmdlcourses',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='helpfulfor',
            name='helpful_for',
            field=models.CharField(choices=[('0', 'Academic Performance'), ('1', 'Project Assignments'), ('2', 'To get job interviews'), ('3', 'To get jobs'), ('4', 'All of the above')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inductionfinallist',
            name='eoi_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='events.InductionInterest'),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='age',
            field=models.CharField(choices=[('', '-----'), ('20to25', '20 to 25 years'), ('26to30', '26 to 30 years'), ('31to35', '31 to 35 years'), ('35andabove', 'Above 35 years')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='borrow_laptop',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='bring_laptop',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='designation',
            field=models.CharField(choices=[('', '-----'), ('Lecturer', 'Lecturer'), ('AssistantProfessor', 'Assistant Professor'), ('AssociateProfessor', 'Associate Professor'), ('Professor', 'Professor'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='do_agree',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='education',
            field=models.CharField(choices=[('', '-----'), ('3yeargraduatedegree(BABScB.Cometc)', '3 year graduate degree (BA, BSc, B.Com, etc.)'), ('Professionaldegree(BEBTechetc)', 'Professional degree (BE, B.Tech, etc.)'), ('2yearMasters(MAMScMCometc)', '2 year Masters (MA, MSc, MCom, etc.)'), ('2yearprofessionalMasters(MEMTechMBAMPhiletc)', '2 year professional Masters (ME, MTech, MBA, MPhil, etc.)'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='experience_in_college',
            field=models.CharField(choices=[('', '-----'), ('Lessthan1year', 'Less than 1 year'), ('Morethan1yearbutlessthan2years', 'More than 1 year, but less than 2 years'), ('Morethan2yearsbutlessthan5years', 'More than 2 years but less than 5 years'), ('Morethan5years', 'More than 5 years')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='gender',
            field=models.CharField(choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='medium_of_studies',
            field=models.CharField(choices=[('', '-----'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bhojpuri', 'Bhojpuri'), ('Bodo', 'Bodo'), ('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Khasi', 'Khasi'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Oriya', 'Oriya'), ('Punjabi', 'Punjabi'), ('Rajasthani', 'Rajasthani'), ('Sanskrit', 'Sanskrit'), ('Santhali', 'Santhali'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='mother_tongue',
            field=models.CharField(choices=[('', '-----'), ('Assamese', 'Assamese'), ('Bengali', 'Bengali'), ('Bhojpuri', 'Bhojpuri'), ('Bodo', 'Bodo'), ('English', 'English'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Kashmiri', 'Kashmiri'), ('Khasi', 'Khasi'), ('Konkani', 'Konkani'), ('Maithili', 'Maithili'), ('Malayalam', 'Malayalam'), ('Manipuri', 'Manipuri'), ('Marathi', 'Marathi'), ('Nepali', 'Nepali'), ('Oriya', 'Oriya'), ('Punjabi', 'Punjabi'), ('Rajasthani', 'Rajasthani'), ('Sanskrit', 'Sanskrit'), ('Santhali', 'Santhali'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='no_objection',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='specialisation',
            field=models.CharField(choices=[('', '-----'), ('Arts', 'Arts'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('EngineeringorComputerScience ', 'Engineering or Computer Science'), ('Management', 'Management'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='invigilator',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='invigilator',
            name='appoved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invigilator_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invigilator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='agegroup',
            field=models.CharField(choices=[('', '-----'), ('below25', 'below 25'), ('25to34', '25 to 34'), ('35to44', '35 to 44'), ('45to54', '45 to 54'), ('55to64', '55 to 64'), ('65andabove', '65 and above')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='currentstatus',
            field=models.CharField(choices=[('', '-----'), ('Student', 'Student'), ('Individuallearner', 'Individual learner'), ('Workingprofessional', 'Working professional'), ('Teacher', 'Teacher'), ('Administrator', 'Administrator'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='did_undergo_st_training',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('NotApplicable ', 'Not Applicable ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='is_drupal_in_curriculum',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('NotApplicable ', 'Not Applicable ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='language',
            field=models.CharField(choices=[('', '-----'), ('Hindi', 'Hindi'), ('English', 'English'), ('Marathi', 'Marathi'), ('Urdu', 'Urdu'), ('Kannanda', 'Kannanda'), ('Bangali', 'Bangali'), ('Malyalum', 'Malyalum'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Oriya', 'Oriya'), ('Assamese', 'Assamese'), ('Gujrati', 'Gujrati')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='like_to_give_testimonial',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='like_to_learn_other_foss',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='need_help_in_organizing',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('NotApplicable ', 'Not Applicable ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='useful_for_placement',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('NotApplicable ', 'Not Applicable ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='useful_for_placement_for_students',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('NotApplicable ', 'Not Applicable ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='when_plan_to_conduct',
            field=models.CharField(choices=[('', '-----'), ('within3months', 'within 3 months'), ('within6months', 'within 6 months'), ('within1year', 'within 1 year'), ('notyetplanned', 'not yet planned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.District'),
        ),
        migrations.AlterField(
            model_name='mediatestimonials',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='mediatestimonials',
            name='workshop_details',
            field=models.CharField(default='Workshop', max_length=255),
        ),
        migrations.AlterField(
            model_name='mumbaistudents',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.StudentBatch'),
        ),
        migrations.AlterField(
            model_name='mumbaistudents',
            name='stuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Student'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='appoved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organiser_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='age',
            field=models.CharField(choices=[('', '-----'), ('<25', '<25 years'), ('25-35', '25-35 years'), ('35+', '35 years and above')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='audio_video_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Verybad', 'Very bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='can_contact',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.City'),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='designation',
            field=models.CharField(choices=[('', '-----'), ('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.District'),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='duration_of_tutorial',
            field=models.CharField(choices=[('', '-----'), ('<0.5', 'Less than 0.5 hour'), ('0.5-2', '0.5 - 2 hour'), ('2-10', '2-10 hours'), ('10+', 'Above 10 hours'), ('NA', 'Not applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='gender',
            field=models.CharField(choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='good_investment',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('Notsure', 'Not sure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='in_side_by_side_method',
            field=models.CharField(choices=[('', '-----'), ('0', 'The video has to be maximized'), ('1', 'The software has to be maximized'), ('2', 'Both software and video are maximized'), ('3', 'None of the above are maximized')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='information_content',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Verybad', 'Very bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_classroom_better',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_comfortable_self_learning',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_got_job',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_help_get_interview',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_help_get_job',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_student_expectations',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='is_training_benefited',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No'), ('Notsure', 'Not sure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='medium_of_instruction',
            field=models.CharField(choices=[('', '-----'), ('English', 'English'), ('Vernacular', 'Vernacular'), ('Mixed', 'Mixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='overall_rating',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Verybad', 'Very bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='presentation_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Verybad', 'Very bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='relevance',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Verybad', 'Very bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='side_by_side_method_is',
            field=models.CharField(choices=[('', '-----'), ('0', 'Explaining the video to a neighbor'), ('1', 'Waiting for mentors explanation'), ('2', 'Watching and practicing simultaneously'), ('3', 'Dont know what this method is')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='side_by_side_yes_no',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='student_education_language',
            field=models.CharField(choices=[('', '-----'), ('English', 'Mostly English'), ('Vernacular', 'Mostly Vernacular'), ('Mixed', 'Mostly Mixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='student_gender',
            field=models.CharField(choices=[('', '-----'), ('Male', 'Mostly Male'), ('Female', 'Mostly Female'), ('Mixed', 'Mixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='student_location',
            field=models.CharField(choices=[('', '-----'), ('Urban', 'Mainly Urban'), ('Rural', 'Mainly Rural'), ('Mixed', 'Mixed'), ('Notsure', 'Not sure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='organisernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='academic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondetails',
            name='paymentdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.PaymentDetails'),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondetails',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permission',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_district', to='events.District'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_district', to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='institute_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_institution_type', to='events.InstituteType'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permissiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.PermissionType'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_state', to='events.State'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_iniversity', to='events.University'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourceperson',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='resourceperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='singletraining',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='singletraining',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.CourseMap'),
        ),
        migrations.AlterField(
            model_name='singletraining',
            name='institution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.InstituteType'),
        ),
        migrations.AlterField(
            model_name='singletraining',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='singletraining',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Organiser'),
        ),
        migrations.AlterField(
            model_name='singletraining',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='singletrainingattendance',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.SingleTraining'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Department'),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Organiser'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.StudentBatch'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Student'),
        ),
        migrations.AlterField(
            model_name='studentstream',
            name='student_stream',
            field=models.CharField(choices=[('0', 'Engineering'), ('1', 'Science'), ('2', 'Arts and Humanities'), ('3', 'Polytechnic/ Diploma programs'), ('4', 'Commerce and Business Studies'), ('5', 'ITI'), ('6', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='acquired_knowledge',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='clarity_of_explanation',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='clarity_of_speech',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='confident_to_apply_knowledge',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='desired_objective',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='diff_instruction',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='difficult_instructions_in_tutorial',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='difficult_simultaneously',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='dont_like_self_learning_method',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='examples_help',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='experience_of_learning',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='flow',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='forum_helpful',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='guidelines',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='help_improve_performance',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='instructions_easy_to_follow',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='interface_comfortable',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='language_diff_to_understand',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='like_to_part',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='logical_sequence',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='method_easy',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='not_like_method_forums',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='not_self_explanatory',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='overall_arrangement',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='overall_content_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='overall_video_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='owing_to_forums',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='pace_of_tutorial',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='plan_to_use_future',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='recommend',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='relevance',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='satisfied',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='self_learning_intrest',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='side_by_side_effective',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='suff_instruction',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='text_readability',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='time_management',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='time_sufficient',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='too_fast',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='too_slow',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='translate',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='useful_learning',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='visual_presentation',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='ws_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='acquired_knowledge',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='adding_func',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='arrangement',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='ask_student_to_use',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='asked_ques_forums',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='can_learn_other',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='clarity_of_speech',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='confident',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='configuration_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='content_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='contents_using_view',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='control_display_images',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='create_new_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='creating_basic_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='creating_dummy_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='desired_objective',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='diff_watch_practice',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='doubts_solved_fast',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='edit_existing_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='esy_to_conduct_own',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='examples_help',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='experience_of_learning',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='faster_on_forums',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='fees',
            field=models.CharField(choices=[('', '-----'), ('below250', 'Below Rs.250/-'), ('between251to500', 'Between Rs.251 to Rs.500/-'), ('between501to1000', 'Between Rs.501 to Rs.1000/-'), ('between1001to2000', 'Between Rs.1001 to Rs.2000/-'), ('above2000', 'Above Rs. 2000/-')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='finding_modules',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='forum_helpful',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='forum_motivated',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='gender',
            field=models.CharField(choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='grp_entity_ref',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='guidelines',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='helpful_pre_ans_ques',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='install_own',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='installation_help',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='installig_ad_themes',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='instructions_easy_to_follow',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='language_complicated',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='learn_other_side_by_side',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='like_to_create_st',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='like_to_part',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='logical_sequence',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='managing_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='menu_endpoints',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='method_easy',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='modify_display_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='modifying_page_layout',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='need_not_post',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='network',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='not_answer_doubts',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='not_have_to_wait',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='not_like_method_forums',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='not_like_reveal_identity',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='not_self_explanatory',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='num_of_experts_req',
            field=models.CharField(choices=[('', '-----'), ('1to10', '1 to 10'), ('11to20', '11 to 20'), ('21to30', '21 to 30'), ('31to40', '31 to 40'), ('above40', 'Above 40')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='other_language',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='overall_arrangement',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='overall_video_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='pace_of_tutorial',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='participated_before',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='people_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='per_asked_ques_before_tuts',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='possible_to_use_therotical',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='recommend',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='referred_forums',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='referred_forums_after',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='relevance',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='satisfied_with_learning_experience',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='side_by_side_hold_intrest',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='sim_framework_before',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='site_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='spfriendly',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='styling_using_themes',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='suff_instruction_by_prof',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='suff_instruction_by_staff',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='table_of_fields_with_views',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='taxonomy',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='text_readability',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='time_for_handson',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='used_sw_before',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='visual_presentation',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='wantto_conduct_incollege',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='ws_not_useful',
            field=models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='ws_quality',
            field=models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='adding_func',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='configuration_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='content_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='contents_using_view',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='control_display_images',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='create_new_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='creating_basic_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='creating_dummy_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='edit_existing_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='finding_modules',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='gender',
            field=models.CharField(choices=[('', '-----'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='grp_entity_ref',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='installig_ad_themes',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='managing_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='menu_endpoints',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='modify_display_content',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='modifying_page_layout',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='people_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='site_management',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='styling_using_themes',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='table_of_fields_with_views',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='taxonomy',
            field=models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='test',
            name='appoved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='test',
            name='invigilator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_invigilator', to='events.Invigilator'),
        ),
        migrations.AlterField(
            model_name='test',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_organiser', to='events.Organiser'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_tests', to='events.TestCategory'),
        ),
        migrations.AlterField(
            model_name='test',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.TrainingRequest'),
        ),
        migrations.AlterField(
            model_name='testattendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Student'),
        ),
        migrations.AlterField(
            model_name='testattendance',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Test'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testimonial_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testimonial_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Test'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='training',
            name='appoved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Course'),
        ),
        migrations.AlterField(
            model_name='training',
            name='extra_fields',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.TrainingExtraFields'),
        ),
        migrations.AlterField(
            model_name='training',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='training',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='training',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Organiser'),
        ),
        migrations.AlterField(
            model_name='trainingattend',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='trainingattend',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Student'),
        ),
        migrations.AlterField(
            model_name='trainingattend',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.TrainingRequest'),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Training'),
        ),
        migrations.AlterField(
            model_name='trainingcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Student'),
        ),
        migrations.AlterField(
            model_name='trainingcertificate',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.TrainingRequest'),
        ),
        migrations.AlterField(
            model_name='trainingfeedback',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.TrainingRequest'),
        ),
        migrations.AlterField(
            model_name='traininglanguagefeedback',
            name='language_prefered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='traininglanguagefeedback',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.TrainingRequest'),
        ),
        migrations.AlterField(
            model_name='traininglivefeedback',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.SingleTraining'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Training'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingplanner',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterField(
            model_name='trainingplanner',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Organiser'),
        ),
        migrations.AlterField(
            model_name='trainingplanner',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Semester'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.StudentBatch'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.CourseMap'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Department'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='training_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.TrainingPlanner'),
        ),
        migrations.AlterField(
            model_name='university',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State'),
        ),
        migrations.AlterField(
            model_name='university',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
