# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20190306_1145'),
        ('events', '0037_auto_20190218_0933'),
    ]

    operations = [
    ]
