# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-18 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_topperlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentbatch',
            unique_together=set([]),
        ),
    ]
