# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-27 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20200618_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='training_end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='training_start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
