# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20200627_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatch',
            name='batch_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
