# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-18 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0043_studentbatch_batch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_key', models.CharField(max_length=50)),
                ('hex_key', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_payer', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=20)),
                ('subscription', models.CharField(choices=[('', '-----'), ('365', 'One_Year'), ('182', 'Six_Months')], max_length=50)),
                ('transactionid', models.CharField(max_length=100, null=True)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('', '-----'), ('New', 'New'), ('Renewal', 'Renewal')], max_length=50)),
                ('college_type', models.CharField(choices=[('', '-----'), ('Engg', 'Engg'), ('ASC', 'ASC'), ('University', 'University')], max_length=50)),
                ('pan_number', models.CharField(max_length=100, null=True)),
                ('gst_number', models.CharField(max_length=15, null=True)),
                ('customer_id', models.CharField(max_length=50, null=True)),
                ('invoice_no', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter')),
                ('entry_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State')),
            ],
        ),
        migrations.AddField(
            model_name='academickey',
            name='ac_pay_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicPaymentStatus'),
        ),
        migrations.AddField(
            model_name='academickey',
            name='academic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
        migrations.AlterUniqueTogether(
            name='academicpaymentstatus',
            unique_together=set([('academic', 'transactionid', 'payment_date')]),
        ),
    ]
