# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_auto_20200718_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpaymentstatus',
            name='college_type',
            field=models.CharField(choices=[('', '-----'), ('Engg', 'Engg'), ('ASC', 'ASC'), ('University', 'University'), ('School', 'School')], max_length=50),
        ),
    ]
