# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_auto_20210318_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattendance',
            name='mdlgrade',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
    ]
