# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-12-31 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20241213_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductioninterest',
            name='college_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inductioninterest',
            name='other_comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learndrupalfeedback',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='any_other_suggestions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organiserfeedback',
            name='testimonial',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='how_make_better',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='like_abt_ws',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedback',
            name='suggestions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='how_make_better',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='like_abt_ws',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='suggestions',
            field=models.TextField(),
        ),
    ]
