# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-01-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20241213_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFeelings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_management', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('configuration_management', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('creating_basic_content', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('edit_existing_content', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('create_new_content', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('grp_entity_ref', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('taxonomy', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('managing_content', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('creating_dummy_content', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('modify_display_content', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('contents_using_view', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('table_of_fields_with_views', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('control_display_images', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('adding_func', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('finding_modules', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('modifying_page_layout', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('menu_endpoints', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('styling_using_themes', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('installig_ad_themes', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('people_management', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
                ('site_management', models.CharField(choices=[('', '-----'), ('Notconfidentatall', 'Not confident at all'), ('Unconfident', 'Unconfident'), ('Neitherconfidentnorunconfident', 'Neither confident nor unconfident'), ('Confident', 'Confident'), ('Absolutelyconfident', 'Absolutely confident'), ('NotApplicable', 'Not Applicable')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spfriendly', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('diff_watch_practice', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('satisfied_with_learning_experience', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('confident', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('side_by_side_hold_intrest', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('ws_not_useful', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('can_learn_other', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('wantto_conduct_incollege', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('esy_to_conduct_own', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('ask_student_to_use', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('possible_to_use_therotical', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('not_self_explanatory', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('logical_sequence', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('examples_help', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('other_language', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('instructions_easy_to_follow', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('language_complicated', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('acquired_knowledge', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('suff_instruction_by_prof', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('suff_instruction_by_staff', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('method_easy', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('desired_objective', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('recommend', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('like_to_part', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('learn_other_side_by_side', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('referred_forums', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('referred_forums_after', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('asked_ques_forums', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('not_answer_doubts', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('forum_helpful', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('doubts_solved_fast', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('need_not_post', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('faster_on_forums', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('not_have_to_wait', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('not_like_method_forums', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('helpful_pre_ans_ques', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('not_like_reveal_identity', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('forum_motivated', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
                ('per_asked_ques_before_tuts', models.CharField(choices=[('', '-----'), ('StronglyAgree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neutral', 'Neutral'), ('Disagree', 'Disagree'), ('StronglyDisagree', 'Strongly Disagree'), ('Noidea', 'No idea')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_quality', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('relevance', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('guidelines', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('overall_video_quality', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('text_readability', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('clarity_of_speech', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('visual_presentation', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('pace_of_tutorial', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('arrangement', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('network', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('installation_help', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('time_for_handson', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('experience_of_learning', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
                ('overall_arrangement', models.CharField(choices=[('', '-----'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Bad', 'Bad'), ('Extremelybad', 'Extremely bad')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='acquired_knowledge',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='adding_func',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='arrangement',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='ask_student_to_use',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='asked_ques_forums',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='can_learn_other',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='clarity_of_speech',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='confident',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='configuration_management',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='content_management',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='contents_using_view',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='control_display_images',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='create_new_content',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='creating_basic_content',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='creating_dummy_content',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='desired_objective',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='diff_watch_practice',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='doubts_solved_fast',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='edit_existing_content',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='esy_to_conduct_own',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='examples_help',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='experience_of_learning',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='faster_on_forums',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='finding_modules',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='forum_helpful',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='forum_motivated',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='grp_entity_ref',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='guidelines',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='helpful_pre_ans_ques',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='installation_help',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='installig_ad_themes',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='instructions_easy_to_follow',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='language_complicated',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='learn_other_side_by_side',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='like_to_part',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='logical_sequence',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='managing_content',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='menu_endpoints',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='method_easy',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='modify_display_content',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='modifying_page_layout',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='need_not_post',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='network',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='not_answer_doubts',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='not_have_to_wait',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='not_like_method_forums',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='not_like_reveal_identity',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='not_self_explanatory',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='other_language',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='overall_arrangement',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='overall_video_quality',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='pace_of_tutorial',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='people_management',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='per_asked_ques_before_tuts',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='possible_to_use_therotical',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='referred_forums',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='referred_forums_after',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='satisfied_with_learning_experience',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='side_by_side_hold_intrest',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='site_management',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='spfriendly',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='styling_using_themes',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='suff_instruction_by_prof',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='suff_instruction_by_staff',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='table_of_fields_with_views',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='text_readability',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='time_for_handson',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='visual_presentation',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='wantto_conduct_incollege',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='ws_not_useful',
        ),
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='ws_quality',
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='explain',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='how_make_better',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='install_own',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='like_abt_ws',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='like_to_create_st',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='sim_framework_before',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='suggestions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stworkshopfeedbackpost',
            name='used_sw_before',
            field=models.CharField(choices=[('', '-----'), ('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='stworkshopfeedbackpost',
            name='feelings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FeedbackFeelings'),
        ),
        migrations.AddField(
            model_name='stworkshopfeedbackpost',
            name='opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FeedbackOpinion'),
        ),
        migrations.AddField(
            model_name='stworkshopfeedbackpost',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FeedbackRate'),
        ),
    ]
