# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-01-09 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20250107_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stworkshopfeedbackpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='STWorkshopFeedbackPost',
        ),
    ]
