# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_auto_20250109_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpaymentstatus',
            name='via_subscription_page',
            field=models.BooleanField(default=False, verbose_name='Payment made via Spoken Tutorial Subscription page?'),
        ),
    ]
