# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-11-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_auto_20251028_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='fossmdlmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.FossMdlCourses'),
        ),
    ]
