# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0032_domain_is_active'),
        ('events', '0053_auto_20251028_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattend',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Level'),
        ),
        migrations.AlterField(
            model_name='trainingattend',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
    ]
