# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-06 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_trainingrequest_fossmdlmap'),
        ('events', '0054_auto_20251104_1245'),
    ]

    operations = [
    ]
