# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-11-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_trainingrequest_fossmdlmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingattend',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='events.TrainingRequest'),
        ),
        migrations.AlterField(
            model_name='trainingrequest',
            name='training_planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='events.TrainingPlanner'),
        ),
    ]
