# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-11-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_merge_20251106_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingattend',
            name='level',
        ),
        migrations.AlterField(
            model_name='trainingattend',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
    ]
