# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-12-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_auto_20251211_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studentmasters', to='events.StudentBatch'),
        ),
        migrations.AlterField(
            model_name='trainingattend',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='events.TrainingRequest'),
        ),
    ]
