# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-11-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_auto_20251130_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaster',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_master', to='events.StudentBatch'),
        ),
    ]
