# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-07-09 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0056_auto_20251212_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicpaymentstatus',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicpaymentstatus',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicpaymentstatus',
            name='verification_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], null=True),
        ),
        migrations.AlterField(
            model_name='academicpaymentstatus',
            name='subscription',
            field=models.CharField(choices=[('', '-----'), ('365', 'One Year (365 days)'), ('182', 'Six Months (182 days)'), ('455', 'Fifteen Months (455 days)')], max_length=50),
        ),
    ]
