# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-12-02 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20251119_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpaymentstatus',
            name='subscription',
            field=models.CharField(choices=[('', '-----'), ('365', 'One_Year'), ('182', 'Six_Months'), ('455', 'Fifteen_Months')], max_length=50),
        ),
    ]
