# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-05 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20251212_0002'),
        ('events', '0057_auto_20251202_1147'),
    ]

    operations = [
    ]
