# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-09 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0058_merge_20260105_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPasswordResetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(default=0, help_text='1 = success, 0 = failed')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.StudentBatch')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_password_reset_history',
                'ordering': ['-changed_on'],
            },
        ),
    ]
