# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-09 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_studentpasswordresethistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentpasswordresethistory',
            options={},
        ),
        migrations.AlterModelTable(
            name='studentpasswordresethistory',
            table=None,
        ),
    ]
