# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='purpose',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
