# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0016_auto_20190918_0536'),
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FossLangDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_foss', to='creation.FossCategory')),
                ('lang', models.ManyToManyField(to='creation.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='foss',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='language',
        ),
        migrations.AddField(
            model_name='fosslangdict',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donate.Payment'),
        ),
    ]
