# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_payee_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPayee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('', '--- Gender ---'), ('M', 'Male'), ('F', 'Female'), ('O', "Don't wish to disclose")], max_length=6)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA')], default='India', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(max_length=2)),
                ('amount', models.CharField(max_length=20)),
                ('reqId', models.CharField(max_length=50)),
                ('transId', models.CharField(max_length=100)),
                ('refNo', models.CharField(max_length=50)),
                ('provId', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=2)),
                ('msg', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('donationDetail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='donate.DonationPayee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goodies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(choices=[('', '--- Gender ---'), ('M', 'Male'), ('F', 'Female'), ('O', "Don't wish to disclose")], max_length=6)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA')], default='India', max_length=6)),
                ('item', models.CharField(choices=[('tshirt', 'T-Shirt')], default='tshirt', max_length=6)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], default='m', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodiesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(max_length=2)),
                ('amount', models.CharField(max_length=20)),
                ('reqId', models.CharField(max_length=50)),
                ('transId', models.CharField(max_length=100)),
                ('refNo', models.CharField(max_length=50)),
                ('provId', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=2)),
                ('msg', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paymentdetail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='donate.Goodies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
