# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-07 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_cdfosslanguages_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymenttransaction',
            unique_together=set([('paymentdetail', 'requestType', 'amount')]),
        ),
    ]
