# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-11 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_donationpayee_donationtransaction_goodies_goodiestransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpayee',
            name='reqId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='goodies',
            name='reqId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payee',
            name='reqId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
