# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-07-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20201113_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='source',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
