# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-09-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_auto_20240902_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionCommonInfo',
        ),
        migrations.RenameField(
            model_name='schooldonationtransactions',
            old_name='school_donation',
            new_name='paymentdetail',
        ),
        migrations.AddField(
            model_name='schooldonation',
            name='mail_response',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldonation',
            name='mail_status',
            field=models.BooleanField(default=False),
        ),
    ]
