# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-19 13:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0051_auto_20250109_1613'),
        ('donate', '0010_auto_20240903_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('expiry_date', models.DateField()),
                ('subscription_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_academic_center', models.IntegerField()),
                ('subscription_days', models.IntegerField()),
                ('subscription_start_date', models.DateField()),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be exactly 10 digits.')])),
                ('response_status', models.CharField(max_length=3)),
                ('error_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSubscriptionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_end_date', models.DateField()),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_details', to='donate.AcademicSubscription')),
            ],
        ),
        migrations.CreateModel(
            name='HDFCTransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('requestId', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=21)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session_error_code', models.CharField(max_length=255)),
                ('session_error_msg', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('order_error_code', models.CharField(max_length=255)),
                ('order_error_msg', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=50)),
                ('udf1', models.TextField()),
                ('udf2', models.TextField()),
                ('udf3', models.CharField(max_length=150)),
                ('udf4', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='academicsubscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donate.HDFCTransactionDetails'),
        ),
        migrations.AddField(
            model_name='academicsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
