# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-11-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_auto_20240903_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='callbackurl',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
