# Generated by Django 5.1.6 on 2025-03-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0025_alter_bankdetail_user_and_more"),
        ("donate", "0012_auto_20250220_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdfosslanguages",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="creation.language"
            ),
        ),
        migrations.AlterField(
            model_name="cdfosslanguages",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="creation.level",
            ),
        ),
    ]
