# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-03-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_auto_20250220_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeeHdfcTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('requestId', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=21)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session_error_code', models.CharField(max_length=255)),
                ('session_error_msg', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('order_error_code', models.CharField(max_length=255)),
                ('order_error_msg', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=50)),
                ('udf1', models.TextField()),
                ('udf2', models.TextField()),
                ('udf3', models.CharField(max_length=150)),
                ('udf4', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='payee',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donate.PayeeHdfcTransaction'),
        ),
    ]
