# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-04-25 09:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_payeehdfctransaction_udf5'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsubscriptiondetail',
            name='gst_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name as per GST'),
        ),
        migrations.AddField(
            model_name='academicsubscriptiondetail',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid GST Number', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')], verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='academicsubscriptiondetail',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN Number', regex='^[A-Z]{5}\\d{4}[A-Z]{1}$')], verbose_name='PAN Number'),
        ),
    ]
