# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-05-05 08:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0015_auto_20250425_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsubscriptiondetail',
            name='pan_number',
        ),
        migrations.AlterField(
            model_name='academicsubscriptiondetail',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid GSTss Number', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')], verbose_name='GST Number'),
        ),
    ]
