# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-05-05 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0017_auto_20250505_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsubscriptiondetail',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number'),
        ),
    ]
