# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creation', '0015_merge_20190621_1204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.TextField()),
                ('narration', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('comment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('data_file', models.FileField(upload_to='scripts')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scriptdetails',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.Scripts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='script_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.ScriptDetails'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
