# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0016_auto_20190918_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_title', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('data_file', models.FileField(upload_to='scripts')),
                ('ordering', models.TextField(default='')),
                ('published_on', models.DateTimeField(null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialDetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.TextField(blank=True)),
                ('narration', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('comment_status', models.BooleanField(default=False)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.Script')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='script_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.ScriptDetail'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
