# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptdetail',
            name='nextRow',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scriptdetail',
            name='prevRow',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
