# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='ordering',
            field=models.CharField(default='', max_length=200),
        ),
    ]
