# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0002_auto_20200304_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='versionNo',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
