# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0002_scripts_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptdetails',
            name='cue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scriptdetails',
            name='narration',
            field=models.TextField(blank=True),
        ),
    ]
