# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0003_auto_20190720_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptdetails',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
