# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0003_script_versionno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='versionNo',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
