# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0004_auto_20200309_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
