# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0005_auto_20190726_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cue', models.TextField(blank=True)),
                ('narration', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('comment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Scripts',
            new_name='Script',
        ),
        migrations.RemoveField(
            model_name='scriptdetails',
            name='script',
        ),
        migrations.AlterField(
            model_name='comment',
            name='script_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.ScriptDetail'),
        ),
        migrations.DeleteModel(
            name='ScriptDetails',
        ),
        migrations.AddField(
            model_name='scriptdetail',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.Script'),
        ),
    ]
