# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scriptmanager', '0005_auto_20190611_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scriptdetails',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.Scripts'),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='data_file',
            field=models.FileField(upload_to='scripts'),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creation.Language'),
        ),
        migrations.AddField(
            model_name='comments',
            name='script_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scriptmanager.ScriptDetails'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
