# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scriptmanager', '0006_auto_20190801_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
    ]
