# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0007_auto_20190705_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language'),
        ),
    ]
