# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0008_auto_20191113_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
