# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0008_auto_20190705_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptdetails',
            name='comment_status',
            field=models.BooleanField(default=False),
        ),
    ]
