# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0009_auto_20191121_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='ordering',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
