# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptmanager', '0010_auto_20191122_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='ordering',
            field=models.TextField(default=''),
        ),
    ]
