# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-02 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='ilw',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='status',
            field=models.CharField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='subscription',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
