# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-03-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20230302_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
