# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-10-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_auto_20260818_1620'),
        ('cms', '0005_auto_20230302_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.AcademicCenter'),
        ),
    ]
