# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20190531_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='cert_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
