# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_trainingrequest_cert_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='topperlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=100)),
                ('userid', models.PositiveIntegerField()),
            ],
        ),
    ]
