# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20201111_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpaymentstatus',
            name='college_type',
            field=models.CharField(choices=[('', '-----'), ('Engg', 'Engg'), ('ASC', 'ASC'), ('Polytechnic', 'Polytechnic'), ('University', 'University'), ('School', 'School')], max_length=50),
        ),
    ]
