# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-12-13 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_testattendance_mdlgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicpaymentstatus',
            name='college_type',
            field=models.CharField(max_length=50),
        ),
    ]
