# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-10-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0032_domain_is_active'),
        ('events', '0052_academicpaymentstatus_via_subscription_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossmdlcourses',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AddField(
            model_name='fossmdlcourses',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Level'),
        ),
    ]
