FOSS_FOLDER = {
    183: "Pregnancy-Breastfeeding-and-Growth-Monitoring",
    184: "6-to-24-Months-Complementary-Feeding",
    185: "Teens-to-Adults-Nutrients-Insulin-and-Recipes",
}

TOPICS_BY_FOSS = {
    183: [
        "Cross cradle hold for breastfeeding",
        "Breastfeeding latching",
        "Importance of Breastfeeding",
        "Importance of Golden Hour and Colostrum Feeding",
        "Comparison of mother's milk with other substitutes",
        "Breastfeeding during COVID-19",
        "Football hold for breastfeeding",
        "Laid back hold for breastfeeding",
        "Side lying hold for breastfeeding",
        "Cradle hold for breastfeeding",
        "Poor weight gain due to improper breastfeeding",
        "Other reasons for not getting enough breast milk",
        "Breast crawl",
        "Preparation for breastfeeding after C-section",
        "Procedure for skin-to-skin contact after C-section",
        "Continuation of skin-to-skin contact after surgery",
        "Kangaroo mother care",
        "Making of a KMC bag with an attached cap",
        "Physical methods to increase the amount of breastmilk",
        "Hand expression of breastmilk",
        "Storage of Expressed Breastmilk",
        "Feeding expressed breast milk to babies",
        "Indian law to protect breastfeeding",
        "Breast conditions in lactating mothers",
        "Nipple conditions in lactating mothers",
        "Complications of using nipple shields",
        "Basics of newborn care",
        "How to bathe a newborn",
        "Vegetarian recipes for lactating mothers",
        "Non-Vegetarian Recipes for Lactating Mothers",
        "Importance of the first 1,000 days of life",
        "WHO weight-for-age percentile growth charts",
        "WHO length-for-age percentile growth charts",
        "WHO length-for-age Z score percentile growth charts",
        "Measurement of children's weight and height",
    ],
    184: [
        "Essential Nutrition Actions for Young Children",
        "Type 1 and type 2 nutrients",
        "Junk food",
        "Reasons for Increase in Junk Food Consumption",
        "Personal Hygiene needed for handling baby food",
        "Safe Preparation, Serving and Storage of Baby Food",
        "General guidelines for complementary feeding",
        "Complementary Food for 6 to 24 Month Old Babies",
        "Nutritious Powder Recipes for 6 to 24 Month Old Children",
        "Vegetarian recipes for 6 month old babies",
        "Non-Vegetarian Recipes for 6 Month Old Babies",
        "Vegetarian recipes for 7 month old babies",
        "Non-Vegetarian Recipes for 7 Month Old Babies",
        "Vegetarian recipes for 8 to 11 month old babies",
        "Non-vegetarian recipes for 8 to 11 month old babies",
        "Vegetarian recipes for 12 to 18 month old babies",
        "Non-Vegetarian Recipes for 12-18 month old babies",
        "Vegetarian recipes for 19 to 24 month old babies",
        "Non-Vegetarian Recipes for 19-24 month old babies",
        "Nutritious vegetarian snacks recipes for children",
        "Nutritious Vegetarian Recipes for Kids Parties",
        "Delicious recipes for kids parties",
    ],
    185: [
        "Vegetarian Recipes for Adolescents",
        "Non-vegetarian Recipes for Adolescents",
        "Pre-pregnancy Nutrition",
        "Essential Nutrition Actions for pregnant women",
        "Vegetarian recipes for pregnant women",
        "Nutritious vegetarian recipes for pregnant women",
        "Non-vegetarian recipes for pregnant women",
        "Nutrient Count of Day to Day Food",
        "Importance of Magnesium",
        "Magnesium rich vegetarian recipes",
        "Non vegetarian recipes enriched with magnesium rich foods",
        "Importance of protein",
        "Protein rich vegetarian recipes",
        "Protein Rich Non-vegetarian Recipes",
        "Importance of Calcium",
        "Calcium rich vegetarian recipes",
        "Calcium Rich Non-vegetarian Recipes",
        "Importance of Vitamin C",
        "Vitamin C rich uncooked recipes",
        "Vitamin C rich cooked recipes",
        "Importance of Folate",
        "Folate rich vegetarian recipes",
        "Folate Rich Non-Vegetarian Recipes",
        "Importance of Vitamin B12",
        "Non-vegetarian Recipes Rich in Vitamin B12",
        "Importance of choline",
        "Choline rich vegetarian recipes",
        "Choline rich non-vegetarian recipes",
        "Importance of Potassium",
        "Potassium rich vegetarian recipes",
        "Potassium rich non-vegetarian recipes",
        "Importance of iron",
        "Iron rich vegetarian recipes",
        "Iron Rich Non-vegetarian Recipes",
        "Importance of Vitamin D",
        "Importance of sulphur",
        "Sulphur Rich Vegetarian Recipe",
        "Importance of Selenium",
        "Selenium Rich Vegetarian Recipes",
        "Importance of Vitamin A",
        "Types of Fats",
        "Fat rich vegetarian recipes",
        "Importance of Insulin",
        "Introduction to Insulin Resistance",
        "Effects of High Levels of Insulin in the Body",
        "Introduction to Macronutrients",
    ],
}