import os
import django
import sys
from django.apps import apps
from django.db import connection


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "spoken.settings")
django.setup()


# 1. Tables managed by Django models
django_tables = {model._meta.db_table for model in apps.get_models()}
# Tables autogenerated due to m2m
m2m_tables = ['auth_group_permissions', 'auth_user_user_permissions','django_migrations', 'events_organiserfeedback_language', 'events_organiserfeedback_trained_foss',
              'certificate_feedback_answer', 'creation_suggesttopic_operating_system' , 'creation_fosscategory_category',
              'events_organiserfeedback_helpful_for', 'events_test_department', 'training_ilwcourse_foss',
              'auth_user_groups', 'events_organiserfeedback_offered_training_foss', 'events_training_department',
              'events_organiserfeedback_student_stream', 'creation_collaborate_contribute_towards', '' ]

db_cache_table = ['topper_cache_table']
external_pkg_models = ['report_builder_report', 'report_builder_format', 'report_builder_displayfield', 'report_builder_filterfield', 'report_builder_report_starred',
                       'captcha_captchastore']


all_active_tables = (django_tables | set(m2m_tables) | set(db_cache_table) | set(external_pkg_models))

# Get current database name (schema)
db_name = connection.settings_dict['NAME']

# 2. Get all tables from MySQL
with connection.cursor() as cursor:
    cursor.execute("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = %s
    """, [db_name])
    db_tables = {row[0] for row in cursor.fetchall()}

# 3. Identify tables NOT managed by Django
manual_tables = db_tables - all_active_tables

print("Manual tables:", sorted(manual_tables))