# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-09-19 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0037_fosscategory_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwayamCourseMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_course_id', models.CharField(max_length=255, unique=True)),
                ('swayam_course_id', models.CharField(blank=True, max_length=255)),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SwayamEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swayam_enrollment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACCESS_PROVISIONED', 'Access Provisioned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], default='ACCESS_PROVISIONED', max_length=30)),
                ('last_reported_progress', models.PositiveSmallIntegerField(default=0)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swayam.SwayamCourseMapping')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwayamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swayam_sub', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swayam_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
