# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-09-28 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwayamTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown_option', models.CharField(max_length=255, verbose_name='Option chosen from dropdown')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('is_logged_in', models.BooleanField(default=False, verbose_name='Is logged in')),
                ('is_subscribed_institution', models.BooleanField(default=False, verbose_name='Is part of a subscribed college/school')),
                ('roles', models.CharField(blank=True, default='', max_length=255, verbose_name='Roles in subscribed institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swayam_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SWAYAM Tracking',
                'verbose_name_plural': 'SWAYAM Trackings',
                'ordering': ['-created'],
            },
        ),
    ]
