# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-09-19 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0037_fosscategory_download'),
        ('swayam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swayamcoursemapping',
            name='foss',
        ),
        migrations.RenameField(
            model_name='swayamenrollment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='swayamenrollment',
            old_name='last_reported_progress',
            new_name='progress_percent',
        ),
        migrations.RenameField(
            model_name='swayamenrollment',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='swayamuser',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='swayamenrollment',
            name='course_mapping',
        ),
        migrations.AddField(
            model_name='swayamenrollment',
            name='foss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='swayam_enrollments', to='creation.FossCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swayamenrollment',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swayamenrollment',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swayamenrollment',
            name='swayam_course_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='swayamuser',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='swayamenrollment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swayam_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swayamuser',
            name='swayam_sub',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='SwayamCourseMapping',
        ),
    ]
