# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-09-28 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_auto_20260818_1620'),
        ('swayam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swayamtracking',
            name='academic_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swayam_trackings', to='events.AcademicCenter', verbose_name='Academic Center'),
        ),
    ]
