# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-09-25 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0037_fosscategory_download'),
        ('swayam', '0002_auto_20260919_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwayamTutorialProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_time', models.FloatField(default=0.0)),
                ('video_duration', models.FloatField(default=0.0)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_progress', to='swayam.SwayamEnrollment')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creation.Language')),
                ('tutorial_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swayam_tutorial_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='swayamtutorialprogress',
            unique_together=set([('user', 'tutorial_detail')]),
        ),
    ]
