# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-09-30 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swayam', '0002_auto_20260919_2128'),
        ('swayam', '0002_swayamtracking_academic_center'),
    ]

    operations = [
    ]
