# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 09:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_koha_ws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.Question'),
        ),
        migrations.AlterField(
            model_name='drupal_camp',
            name='purpose',
            field=models.CharField(default='DCM', max_length=10),
        ),
        migrations.AlterField(
            model_name='drupal_ws',
            name='purpose',
            field=models.CharField(default='DRP', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='purpose',
            field=models.CharField(choices=[('DCM', 'DrupalCamp Mumbai'), ('DRP', 'Drupal Workshop'), ('FAW', 'FrontAccounting Workshop')], max_length=25),
        ),
        migrations.AlterField(
            model_name='fa_ws',
            name='purpose',
            field=models.CharField(default='FAW', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='purpose',
            field=models.CharField(default='SLC', max_length=10),
        ),
        migrations.AlterField(
            model_name='itp_ws',
            name='purpose',
            field=models.CharField(default='ITP', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_ws',
            name='purpose',
            field=models.CharField(default='KHW', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='purpose',
            field=models.CharField(default='SLC', max_length=10),
        ),
    ]
