# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0011_auto_20190218_0933'),
        ('certificate', '0012_koha_ws_12oct2018'),
    ]

    operations = [
    ]
