# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0013_merge_20190222_0555'),
        ('certificate', '0013_koha_rc_12oct2018'),
    ]

    operations = [
    ]
