# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0014_merge_20190520_1334'),
        ('certificate', '0017_moodle_ws_15mar2019'),
    ]

    operations = [
    ]
