# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0017_moodle_ws_15mar2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.Question'),
        ),
        migrations.AlterField(
            model_name='drupal_camp',
            name='purpose',
            field=models.CharField(default='DCM', max_length=10),
        ),
        migrations.AlterField(
            model_name='drupal_ws',
            name='purpose',
            field=models.CharField(default='DRP', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='purpose',
            field=models.CharField(choices=[('DCM', 'DrupalCamp Mumbai'), ('DRP', 'Drupal Workshop'), ('FAW', 'FrontAccounting Workshop')], max_length=25),
        ),
        migrations.AlterField(
            model_name='fa_ws',
            name='purpose',
            field=models.CharField(default='FAW', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='purpose',
            field=models.CharField(default='SLC', max_length=10),
        ),
        migrations.AlterField(
            model_name='itp_ws',
            name='purpose',
            field=models.CharField(default='ITP', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_rc_12oct2018',
            name='purpose',
            field=models.CharField(default='KRC', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_ws',
            name='purpose',
            field=models.CharField(default='KHW', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_ws_12oct2018',
            name='purpose',
            field=models.CharField(default='KMW', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_ws_29sep2018',
            name='purpose',
            field=models.CharField(default='KCW', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_ws_8feb2019',
            name='purpose',
            field=models.CharField(default='KCW', max_length=10),
        ),
        migrations.AlterField(
            model_name='koha_ws_9march2019',
            name='purpose',
            field=models.CharField(default='KMW', max_length=10),
        ),
        migrations.AlterField(
            model_name='moodle_ws_15mar2019',
            name='purpose',
            field=models.CharField(default='MMW', max_length=10),
        ),
        migrations.AlterField(
            model_name='moodle_ws_1march2019',
            name='purpose',
            field=models.CharField(default='MCW', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='purpose',
            field=models.CharField(default='SLC', max_length=10),
        ),
    ]
