# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0019_koha_rc_9march2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moodle_RC_15march2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('usertype', models.CharField(default='cc', max_length=10)),
                ('rcid', models.CharField(max_length=500)),
                ('remote', models.CharField(max_length=500)),
                ('purpose', models.CharField(default='MRC', max_length=10)),
            ],
        ),
    ]
