# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0020_moodle_rc_15march2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='koha_rc_12oct2018',
            name='usertype',
            field=models.CharField(default='rcc', max_length=10),
        ),
    ]
