EVENTS_DEPARTMENTS = [
    "Aeronautical Engineering",
    "Aerospace",
    "Agricultural Process and Food Engineering",
    "Agriculture",
    "Applied Mathematics",
    "Applied Physics",
    "Arabic",
    "Architecture",
    "Arts ",
    "Audio and Speech Language Pathology",
    "Automobile Engineering",
    "Avionics",
    "B. Pharm Degree",
    "B. Sc. Computer Science",
    "B.A (Economics)",
    "B.A Mathematics",
    "B.A. (I.T.)",
    "B.A. Sociology with Computer Applications",
    "B.Com Finance",
    "B.Com in Banking and Insurance (B.B.I)",
    "B.Com Professional Accounting",
    "B.Com. (I.T.)",
    "B.Com. with Computer Applications",
    "B.Sc Catering and Hotel Management",
    "B.Sc Clinical and Laboratory Technology",
    "B.Sc in Chemistry",
    "B.Sc in Physics",
    "B.Sc. Mathematics",
    "B.Tech Agriculture Engineering",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Business Management (BBM)",
    "Bachelor of Computer Application (BCA)",
    "Bachelor of Science (Bsc)",
    "Bachelor of Science in Information Technology (BSc. IT)",
    "Bachelor of Technology (BTech)",
    "Bachelor of Vocational (B.Voc)",
    "BBA (CA) ",
    "Biochemical Engineering",
    "Bioinformatics",
    "Biology",
    "Biomedical Engineering",
    "Biotechnology",
    "BSc Software Systems",
    "Catering Science & Hotel Management ",
    "CBSE",
    "Chemical Engineering",
    "Chemistry",
    "Civil and Environmental Engineering (B.Tech)",
    "Civil and Environmental Engineering (M.Tech)",
    "Civil Engineering (B.Tech)",
    "Civil Engineering (M.Tech)",
    "Civil Engineering",
    "Commerce and Management",
    "Commerce",
    "Computer Application and Business Management",
    "Computer Applications",
    "Computer Engineering",
    "Computer Science and Applications",
    "Computer Science and Engineering (B.Tech)",
    "Computer Science and Engineering (M.Tech)",
    "Computer Science and Engineering",
    "Computer Science and Information Technology (CSIT)",
    "Computer Science and Technology",
    "Computer Science",
    "Computer Technology",
    "Cosmetology & Health",
    "Department of Electronics & Video Engineering",
    "Department of Foods and Nutrition",
    "Dual Degree MBA",
    "Earth Sciences",
    "Electrical and Electronics Engineering (B. Tech)",
    "Electrical and Electronics Engineering (EEE)",
    "Electrical Engineering",
    "Electrical, Electronics and Communication Engineering (EECE)",
    "Electronics & Communication Systems",
    "Electronics and Communication Engineering (B.Tech)",
    "Electronics and Communication Engineering (M.Tech)",
    "Electronics and Communication Engineering",
    "Electronics and Computer Engineering",
    "Electronics and instrumentation Engineering",
    "Electronics and Telecommunication",
    "Electronics Engineering",
    "English",
    "Geography",
    "Harbour Engineering",
    "HND-ME",
    "HND-Nautical Science",
    "Home Science Extension and Communication Management",
    "IIT Bombay PG Council ",
    "Industrial Electronics",
    "Information Science",
    "Information Technology",
    "Instrumentation and  Control Engineering",
    "Instrumentation",
    "Interior Decoration & Design",
    "Law",
    "M. Pharm Degree",
    "M. Tech Computer Science",
    "M.A. Sociology",
    "M.Com International Business",
    "M.Com",
    "M.Com. with Computer Applications",
    "M.Phil.",
    "M.Sc (Medical Physics)",
    "M.Sc in Chemistry",
    "M.Sc in Physics",
    "M.Sc. counselling Psychology",
    "M.Sc. Mathematics",
    "M.Sc. Software Systems",
    "M.Tech Information Technology",
    "Marine Biotechnology",
    "Marine Engineering",
    "Mass Communication",
    "Master of Business Administration",
    "Master of Business Management (MBM)",
    "Master of Computer Science ",
    "Master of Human Resource Management",
    "Master of Science (Msc)",
    "Master of Science in Information Technology (Msc. IT)",
    "Master of Social Work (MSW)",
    "Masters of Computer Management",
    "Mathematics",
    "MCA ( Integrated) ",
    "MCA",
    "Mechanical and Automation Engineering",
    "Mechanical Design Engineering",
    "Mechanical Engineering (B.Tech)",
    "Mechanical Engineering (M.Tech)",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Metallurgy and Materials Engineering",
    "Modern Office Practice (Engineering)",
    "Modern Office Practice (English)",
    "Modern Office Practice (Hindi)",
    "Nautical Science",
    "Naval Architecture and Offshore Engineering",
    "Non Teaching Staff",
    "Nursing",
    "Others",
    "Petrochemical Engineering",
    "Petroleum Engineering",
    "PG Council IIT Bombay",
    "PGDCA",
    "PGDM",
    "Physical Education",
    "Physical Science",
    "Physics",
    "Physiotherapy",
    "Polytechnic",
    "Post Graduate Diploma in Geoinformatics",
    "Production Engineering",
    "Production Technology",
    "Rubber and Plastics Technology",
    "Sanskrit",
    "School",
    "Science",
    "Scilab (Image Processing RS and GIS)",
    "Shipbuilding Engineering",
    "Soil and Water Engineering",
    "Structural Engineering",
    "Telecommunication Engineering",
    "Textile Engineering",
    "Thermal Engineering",
    "Tool and Die Engineering",
]
