# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 09:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdldjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdluser',
            name='academic_code',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdluser',
            name='age_range',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdluser',
            name='flag',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdluser',
            name='gender',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdluser',
            name='invigilator',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdluser',
            name='organizer',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
