# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ILWMdlEnrol',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('enrol', models.CharField(max_length=60)),
                ('status', models.BigIntegerField()),
                ('courseid', models.BigIntegerField()),
                ('sortorder', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=765)),
                ('enrolperiod', models.BigIntegerField(blank=True, null=True)),
                ('enrolstartdate', models.BigIntegerField(blank=True, null=True)),
                ('enrolenddate', models.BigIntegerField(blank=True, null=True)),
                ('expirynotify', models.IntegerField(blank=True, null=True)),
                ('expirythreshold', models.BigIntegerField(blank=True, null=True)),
                ('notifyall', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('cost', models.CharField(blank=True, max_length=60)),
                ('currency', models.CharField(blank=True, max_length=9)),
                ('roleid', models.BigIntegerField(blank=True, null=True)),
                ('customint1', models.BigIntegerField(blank=True, null=True)),
                ('customint2', models.BigIntegerField(blank=True, null=True)),
                ('customint3', models.BigIntegerField(blank=True, null=True)),
                ('customint4', models.BigIntegerField(blank=True, null=True)),
                ('customint5', models.BigIntegerField(blank=True, null=True)),
                ('customint6', models.BigIntegerField(blank=True, null=True)),
                ('customint7', models.BigIntegerField(blank=True, null=True)),
                ('customint8', models.BigIntegerField(blank=True, null=True)),
                ('customchar1', models.CharField(blank=True, max_length=765)),
                ('customchar2', models.CharField(blank=True, max_length=765)),
                ('customchar3', models.CharField(blank=True, max_length=3999)),
                ('customdec1', models.DecimalField(blank=True, decimal_places=7, max_digits=14, null=True)),
                ('customdec2', models.DecimalField(blank=True, decimal_places=7, max_digits=14, null=True)),
                ('customtext1', models.TextField(blank=True)),
                ('customtext2', models.TextField(blank=True)),
                ('customtext3', models.TextField(blank=True)),
                ('customtext4', models.TextField(blank=True)),
                ('timecreated', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_enrol',
            },
        ),
        migrations.CreateModel(
            name='ILWMdlQuizAttempts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quiz', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('attempt', models.IntegerField(unique=True)),
                ('uniqueid', models.BigIntegerField(unique=True)),
                ('layout', models.TextField()),
                ('currentpage', models.BigIntegerField()),
                ('preview', models.IntegerField()),
                ('state', models.CharField(max_length=48)),
                ('timestart', models.BigIntegerField()),
                ('timefinish', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
                ('timemodifiedoffline', models.BigIntegerField()),
                ('timecheckstate', models.BigIntegerField(blank=True, null=True)),
                ('sumgrades', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'mdl_quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='ILWMdlQuizGrades',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quiz', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('grade', models.DecimalField(decimal_places=5, max_digits=12)),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_quiz_grades',
            },
        ),
        migrations.CreateModel(
            name='ILWMdlRoleAssignments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('roleid', models.BigIntegerField()),
                ('contextid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
                ('modifierid', models.BigIntegerField()),
                ('component', models.CharField(max_length=300)),
                ('itemid', models.BigIntegerField()),
                ('sortorder', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_role_assignments',
            },
        ),
        migrations.CreateModel(
            name='ILWMdlUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=96)),
                ('idnumber', models.CharField(max_length=765)),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mdl_user',
            },
        ),
        migrations.CreateModel(
            name='ILWMdlUserEnrolments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.BigIntegerField()),
                ('enrolid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('timestart', models.BigIntegerField()),
                ('timeend', models.BigIntegerField()),
                ('modifierid', models.BigIntegerField()),
                ('timecreated', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_user_enrolments',
            },
        ),
    ]
