# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='foss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
    ]
