# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-06-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20190531_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
