# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-06-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20190531_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='Enter an IP address or CIDR range (IPv4/IPv6)', max_length=43, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
