# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0012_tutorialresource_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreviewernotification',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='adminreviewernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminreviewlog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='adminreviewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivedvideo',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='archivedvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brochuredocument',
            name='foss_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='brochuredocument',
            name='foss_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='brochurepage',
            name='brochure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='creation.BrochureDocument'),
        ),
        migrations.AlterField(
            model_name='brochurepage',
            name='page',
            field=models.FileField(upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='collaborate',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='collaborate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributorlog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='contributorlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributornotification',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='contributornotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributorrole',
            name='foss_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='contributorrole',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='contributorrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domainreviewernotification',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='domainreviewernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domainreviewerrole',
            name='foss_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='domainreviewerrole',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='domainreviewerrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domainreviewlog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='domainreviewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fossavailablefortest',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='fossavailablefortest',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='fossavailableforworkshop',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='fossavailableforworkshop',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='fosscategory',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='If unchecked, this foss will be displayed on series page, instead of home page'),
        ),
        migrations.AlterField(
            model_name='fosscategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='needimprovementlog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='needimprovementlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistinfo',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='playlistinfo',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.PlaylistInfo'),
        ),
        migrations.AlterField(
            model_name='publicreviewlog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='publicreviewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishtutoriallog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='publishtutoriallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreviewernotification',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='qualityreviewernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreviewerrole',
            name='foss_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='qualityreviewerrole',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='qualityreviewerrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityreviewlog',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='qualityreviewlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='approved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestexample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggesttopic',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Level'),
        ),
        migrations.AlterField(
            model_name='suggesttopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='additional_material_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_material', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='assignment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='code_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='keyword_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite', to='creation.TutorialDetail'),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='prerequisite_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='slide_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialcommoncontent',
            name='tutorial_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tutorial_detail', to='creation.TutorialDetail'),
        ),
        migrations.AlterField(
            model_name='tutorialdetail',
            name='foss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='tutorialdetail',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Level'),
        ),
        migrations.AlterField(
            model_name='tutorialdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialmissingcomponent',
            name='tutorial_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
        migrations.AlterField(
            model_name='tutorialmissingcomponent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raised_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialmissingcomponentreply',
            name='missing_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialMissingComponent'),
        ),
        migrations.AlterField(
            model_name='tutorialmissingcomponentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='common_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialCommonContent'),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='outline_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='script_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='tutorial_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialDetail'),
        ),
        migrations.AlterField(
            model_name='tutorialresource',
            name='video_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
