# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 11:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0013_auto_20190531_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'language'),
            },
        ),
        migrations.CreateModel(
            name='TutorialsAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.Language')),
                ('tutorial_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialDetail')),
            ],
        ),
        migrations.AddField(
            model_name='contributorrole',
            name='tutorial_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialDetail'),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='is_translation_allowed',
            field=models.BooleanField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='rolerequest',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creation.Language'),
        ),
        migrations.AddField(
            model_name='tutorialresource',
            name='assignment_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorialresource',
            name='extension_status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorialresource',
            name='submissiondate',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 2, 12, 0)),
        ),
        migrations.AlterUniqueTogether(
            name='contributorrole',
            unique_together=set([('user', 'tutorial_detail', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolerequest',
            unique_together=set([('user', 'role_type', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='tutorialsavailable',
            unique_together=set([('tutorial_detail', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='languagemanager',
            unique_together=set([('user', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='contributorrating',
            unique_together=set([('user', 'language')]),
        ),
    ]
