# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0013_auto_20181112_1047'),
        ('creation', '0013_auto_20190218_0933'),
    ]

    operations = [
    ]
