# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0013_auto_20190531_0944'),
        ('creation', '0014_remove_tutorialdetail_script_status'),
    ]

    operations = [
    ]
