# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0014_auto_20190820_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=15)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialDetail')),
            ],
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='available_for_nasscom',
            field=models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for nasscom'),
        ),
    ]
