# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0014_auto_20190820_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='available_for_nasscom',
            field=models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for nasscom'),
        ),
    ]
