# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0015_auto_20190904_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=17)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHonorarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('code', models.CharField(editable=False, max_length=20)),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'In Process'), (2, 'Forwarded'), (3, 'Completed'), (4, 'Confirmed')], default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Script User'), (2, 'Video User'), (3, 'Script & Video User')], default=3)),
                ('seconds', models.PositiveIntegerField(default=0, help_text='Tutorial duration in seconds')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Payment Cancelled'), (1, 'Payment Due'), (2, 'Payment Initiated')], default=1)),
                ('payment_honorarium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='creation.PaymentHonorarium')),
                ('tutorial_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialResource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tutorialpayment',
            unique_together=set([('tutorial_resource', 'user')]),
        ),
    ]
