# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-18 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0015_auto_20190904_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosscategory',
            name='show_on_homepage',
            field=models.PositiveSmallIntegerField(default=0, help_text='0:Display on home page, 1:Series, 2:Archived'),
        ),
    ]
