# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0016_auto_20190918_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialduration',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='tutorialduration',
            name='tresource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.TutorialResource'),
        ),
    ]
