# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0016_auto_20190918_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosscategory',
            name='show_on_homepage',
            field=models.PositiveSmallIntegerField(default=0, help_text='0:H&N, 1:Display on home page, 2:Archived, 3:series, 4:covid'),
        ),
    ]
