# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0018_tutorialduration_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='available_for_jio',
            field=models.BooleanField(default=True, help_text='If unchecked, this foss will not be available for jio and spoken-tutorial.in'),
        ),
    ]
