# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0019_fosscategory_available_for_jio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosscategory',
            name='show_on_homepage',
            field=models.PositiveSmallIntegerField(default=0, help_text='0:Series, 1:Display on home page, 2:Archived'),
        ),
    ]
