# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0019_auto_20201214_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='account_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
