# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-28 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0019_fosscategory_available_for_jio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default=None, max_length=100)),
                ('account_number', models.CharField(max_length=17)),
                ('bankaddress', models.CharField(default=None, max_length=255)),
                ('pancard', models.CharField(default=None, max_length=10)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=100)),
                ('pincode', models.CharField(default=0, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.CharField(default=0, max_length=11)),
                ('vendoraddress', models.CharField(default=None, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHonorarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('code', models.CharField(editable=False, max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'In Process'), (2, 'Forwarded'), (3, 'Completed'), (4, 'Confirmed'), (5, 'Agreement Accepted'), (6, 'Receipt Accepted'), (11, 'All accepted and closed')], default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Script User'), (2, 'Video User'), (3, 'Script & Video User')], default=3)),
                ('seconds', models.PositiveIntegerField(default=0, help_text='Tutorial duration in seconds')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Payment Cancelled'), (1, 'Payment Due'), (2, 'Payment Initiated')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_honorarium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to='creation.PaymentHonorarium')),
                ('tutorial_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialResource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='fosscategory',
            name='show_on_homepage',
            field=models.PositiveSmallIntegerField(default=0, help_text='0:Series, 1:Display on home page, 2:Archived'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorialpayment',
            unique_together=set([('tutorial_resource', 'user')]),
        ),
    ]
