# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0020_auto_20201221_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='bankaddress',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='pancard',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
