# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-04-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0020_auto_20220328_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosssupercategory',
            name='part_of_recsys',
            field=models.BooleanField(default=False, max_length=2),
        ),
        migrations.AddField(
            model_name='fosssupercategory',
            name='specialisation',
            field=models.CharField(default='Programming Language', max_length=255),
        ),
    ]
