# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-17 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0021_auto_20201228_1843'),
        ('creation', '0020_auto_20211105_1731'),
    ]

    operations = [
    ]
