# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-01-12 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0021_auto_20220705_1453'),
        ('creation', '0021_auto_20220426_0206'),
    ]

    operations = [
    ]
