# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-14 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creation', '0022_merge_20211217_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthonorarium',
            name='doc',
        ),
        migrations.AddField(
            model_name='paymenthonorarium',
            name='initiated_by',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to=settings.AUTH_USER_MODEL),
        ),
    ]
