# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-01-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0022_merge_20230112_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
