# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-06-17 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0024_fosscategory_is_fossee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialSummaryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_count', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creation.TutorialResource')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.FossCategory', unique=True)),
            ],
        ),
    ]
