# Generated by Django 5.1.6 on 2025-03-18 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creation", "0024_fosscategory_is_fossee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="user",
            field=models.OneToOneField(
                limit_choices_to=models.Q(("groups__name", "External-Contributor")),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contributorrating",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="creation.language"
            ),
        ),
        migrations.AlterField(
            model_name="contributorrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contributorrole",
            name="tutorial_detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="creation.tutorialdetail",
            ),
        ),
        migrations.AlterField(
            model_name="languagemanager",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="creation.language"
            ),
        ),
        migrations.AlterField(
            model_name="languagemanager",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="paymenthonorarium",
            name="initiated_by",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rolerequest",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="creation.language",
            ),
        ),
        migrations.AlterField(
            model_name="tutorialpayment",
            name="tutorial_resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="creation.tutorialresource",
            ),
        ),
        migrations.AlterField(
            model_name="tutorialpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tutorialsavailable",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="creation.language"
            ),
        ),
        migrations.AlterField(
            model_name="tutorialsavailable",
            name="tutorial_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="creation.tutorialdetail",
            ),
        ),
    ]
