# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-08-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0025_tutorialsummarycache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialresource',
            name='is_unrestricted',
            field=models.BooleanField(default=False),
        ),
    ]
