# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-08-22 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0027_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='domain',
            field=models.ManyToManyField(to='creation.Domain'),
        ),
    ]
