# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0028_fosscategory_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='domain_icons/'),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='foss_icons/'),
        ),
    ]
