# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0029_auto_20250912_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosscategoryDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.Domain')),
            ],
        ),
        migrations.RemoveField(
            model_name='fosscategory',
            name='domain',
        ),
        migrations.AddField(
            model_name='fosscategorydomain',
            name='fosscategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='fosscategorydomain',
            unique_together=set([('fosscategory', 'domain')]),
        ),
    ]
