# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0030_auto_20250914_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
