# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0031_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
