# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-01-01 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0032_domain_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='additional_software',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='disk_space',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='duration_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosscategory',
            name='ram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
