# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-01-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0033_auto_20260101_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialresource',
            name='is_on_youtube',
            field=models.BooleanField(default=False),
        ),
    ]
