# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-07-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0034_tutorialresource_is_on_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialresource',
            name='is_hst',
            field=models.BooleanField(default=False),
        ),
    ]
