# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-08-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0035_tutorialresource_is_hst'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='order',
            field=models.IntegerField(default=0, help_text='Enter the display order. Smaller numbers will be displayed first.'),
            preserve_default=False,
        ),
    ]
