from django.db import models

class MdlUser(models.Model):
    id = models.BigIntegerField(primary_key=True)
    auth = models.CharField(max_length=60)
    confirmed = models.IntegerField()
    #policyagreed = models.IntegerField()
    #deleted = models.IntegerField()
    #suspended = models.IntegerField()
    mnethostid = models.BigIntegerField(unique=True)
    username = models.CharField(unique=True, max_length=255)
    password = models.CharField(max_length=96)
    idnumber = models.CharField(max_length=765)
    firstname = models.CharField(max_length=300)
    lastname = models.CharField(max_length=300)
    email = models.CharField(max_length=300)
    #emailstop = models.IntegerField()
    icq = models.CharField(max_length=45)
    skype = models.CharField(max_length=150)
    yahoo = models.CharField(max_length=150)
    aim = models.CharField(max_length=150)
    msn = models.CharField(max_length=150)
    phone1 = models.CharField(max_length=60)
    phone2 = models.CharField(max_length=60)
    institution = models.CharField(max_length=120)
    department = models.CharField(max_length=90)
    address = models.CharField(max_length=210)
    city = models.CharField(max_length=360)
    country = models.CharField(max_length=6)
    #lang = models.CharField(max_length=90)
    theme = models.CharField(max_length=150)
    timezone = models.CharField(max_length=300)
    #firstaccess = models.BigIntegerField()
    #lastaccess = models.BigIntegerField()
    #lastlogin = models.BigIntegerField()
    #currentlogin = models.BigIntegerField()
    lastip = models.CharField(max_length=135)
    secret = models.CharField(max_length=45)
    #picture = models.BigIntegerField()
    url = models.CharField(max_length=765)
    description = models.TextField(blank=True)
    #descriptionformat = models.IntegerField()
    #mailformat = models.IntegerField()
    #maildigest = models.IntegerField()
    #maildisplay = models.IntegerField()
    #htmleditor = models.IntegerField()
    #autosubscribe = models.IntegerField()
    #trackforums = models.IntegerField()
    #timecreated = models.BigIntegerField()
    #timemodified = models.BigIntegerField()
    #trustbitmask = models.BigIntegerField()
    imagealt = models.CharField(max_length=765, blank=True)
    class Meta:
        db_table = u'mdl_user'
        
class MdlQuizGrades(models.Model):
    id = models.BigIntegerField(primary_key=True)
    quiz = models.BigIntegerField()
    userid = models.BigIntegerField()
    grade = models.DecimalField(max_digits=12, decimal_places=5)
    timemodified = models.BigIntegerField()
    class Meta:
        db_table = u'mdl_quiz_grades'

class MdlQuizAttempts(models.Model):
    id = models.BigIntegerField(primary_key=True)
    quiz = models.BigIntegerField()
    userid = models.BigIntegerField()
    attempt = models.IntegerField(unique=True)
    uniqueid = models.BigIntegerField(unique=True)
    layout = models.TextField()
    currentpage = models.BigIntegerField()
    preview = models.IntegerField()
    state = models.CharField(max_length=48)
    timestart = models.BigIntegerField()
    timefinish = models.BigIntegerField()
    timemodified = models.BigIntegerField()
    timecheckstate = models.BigIntegerField(null=True, blank=True)
    sumgrades = models.DecimalField(null=True, max_digits=12, decimal_places=5, blank=True)
    needsupgradetonewqe = models.IntegerField()
    class Meta:
        db_table = u'mdl_quiz_attempts'

