# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0018_tutorialduration_created'),
        ('donate', '0002_payee_purpose'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='foss_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='donate.Payee'),
        ),
        migrations.AddField(
            model_name='participant',
            name='reg_approval_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='registartion_type',
            field=models.PositiveSmallIntegerField(choices=[('', '-----'), (1, 'Subscribed College'), (2, 'Manual Registration')], default=1),
        ),
        migrations.AddField(
            model_name='trainingevents',
            name='training_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingevents',
            name='event_type',
            field=models.CharField(choices=[('', '-----'), ('FDP', 'Paid FDP'), ('Workshop', 'Blended Mode Workshop'), ('sdp', 'Student Training Programme')], max_length=50),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.TrainingEvents'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.Participant'),
        ),
    ]
