# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0018_tutorialduration_created'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='foss_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.Language'),
        ),
        migrations.AlterField(
            model_name='trainingevents',
            name='event_type',
            field=models.CharField(choices=[('', '-----'), ('FDP', 'Paid FDP'), ('Workshop', 'Blended Mode Workshop')], max_length=50),
        ),
    ]
