# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200727_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='training_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
