# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200807_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='event_fee',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
