# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-29 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingevents_training_status'),
        ('training', '0002_auto_20200728_1400'),
    ]

    operations = [
    ]
