# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-17 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_payee_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0004_trainingevents_event_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50)),
                ('counter', models.IntegerField()),
                ('paper', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.IntegerField(default=0)),
                ('serial_key', models.CharField(max_length=200, null=True)),
                ('short_key', models.CharField(max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.TrainingEvents')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('event', 'user', 'payment_status')]),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.Participant'),
        ),
    ]
