# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-31 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_payee_purpose'),
        ('training', '0004_merge_20200729_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='donate.Payee'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registartion_type',
            field=models.PositiveSmallIntegerField(choices=[('', '-----'), ('1', 'Subscribed College'), ('2', 'Manual Registration')], default=1),
        ),
        migrations.AlterField(
            model_name='trainingevents',
            name='event_type',
            field=models.CharField(choices=[('', '-----'), ('FDP', 'Paid FDP'), ('Workshop', 'Blended Mode Workshop'), ('sdp', 'Student Training Programme')], max_length=50),
        ),
    ]
