# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-04 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20200731_1852'),
        ('training', '0005_auto_20200731_1625'),
    ]

    operations = [
    ]
