# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_merge_20200804_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reg_approval_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registartion_type',
            field=models.PositiveSmallIntegerField(choices=[('', '-----'), (1, 'Subscribed College'), (2, 'Manual Registration')], default=1),
        ),
    ]
