# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0018_tutorialduration_created'),
        ('training', '0006_auto_20201111_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILWFossMdlCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdlcourse_id', models.PositiveIntegerField()),
                ('mdlquiz_id', models.PositiveIntegerField()),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory')),
            ],
        ),
    ]
