# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_eventteststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteststatus',
            name='cert_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
