# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_eventteststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventteststatus',
            name='mdlattempt_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
