# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0018_tutorialduration_created'),
        ('training', '0009_eventteststatus_cert_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilwfossmdlcourses',
            name='testfoss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testfoss', to='creation.FossCategory'),
        ),
        migrations.AlterField(
            model_name='ilwfossmdlcourses',
            name='foss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventfoss', to='creation.FossCategory'),
        ),
    ]
