# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-01-27 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20210425_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilwfossmdlcourses',
            options={'ordering': ['foss']},
        ),
    ]
