# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_testattendance_mdlgrade'),
        ('training', '0013_auto_20240516_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='events.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='events.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training.CompanyType'),
        ),
    ]
