# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-03-06 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0024_fosscategory_is_fossee'),
        ('training', '0015_participant_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILWCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('foss', models.ManyToManyField(related_name='courses', to='creation.FossCategory')),
            ],
        ),
        migrations.AddField(
            model_name='trainingevents',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='training.ILWCourse'),
        ),
    ]
