# Generated by Django 5.1.6 on 2025-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0015_participant_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingevents",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("", "-----"),
                    ("FDP", "Faculty Development Program (FDP)"),
                    ("Workshop", "Blended Mode Workshop"),
                    ("sdp", "Student Training Programme"),
                    ("TPDP", "Teachers Professional Development Program"),
                    ("SSDP", "School Students  Development Program"),
                    ("PDP", "Professional Development Program"),
                    ("CDP", "Community Development Program"),
                ],
                max_length=50,
            ),
        ),
    ]
