# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-03-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20250306_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingevents',
            name='foss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creation.FossCategory'),
        ),
    ]
