# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-03-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20250306_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='is_course',
            field=models.BooleanField(default=False),
        ),
    ]
