# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-03-21 13:06
from __future__ import unicode_literals

from django.db import migrations

# Migration file to create course records from existing ilw foss

def set_default_course(apps, schema_editor):
    ILWCourse = apps.get_model('training', 'ILWCourse')
    TrainingEvents = apps.get_model('training', 'TrainingEvents')
    # FossCategory = apps.get_model('creation', 'FossCategory')

    for item in TrainingEvents.objects.all():
        course = ILWCourse.objects.create()
        course.foss.add(item.foss)
        item.course = course
        item.save()
        
  
class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_trainingevents_is_course'),
    ]

    operations = [
        migrations.RunPython(set_default_course)
    ]
