# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-07-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20250708_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='language_hn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
