# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-07-17 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20250709_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
