# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-08-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_trainingevents_instructor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEventCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_course', models.IntegerField()),
                ('mdl_quiz', models.IntegerField()),
                ('mdl_course', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trainingevents',
            name='event_type',
            field=models.CharField(choices=[('', '-----'), ('FDP', 'Faculty Development Program (FDP)'), ('Workshop', 'Blended Mode Workshop'), ('sdp', 'Student Training Programme'), ('TPDP', 'Teachers Professional Development Program'), ('SSDP', 'School Students  Development Program'), ('PDP', 'Professional Development Program'), ('CDP', 'Community Development Program'), ('HN', 'Health And Nutrition Program'), ('INTERN', 'Internship Programme')], max_length=50),
        ),
        migrations.AddField(
            model_name='externaleventcourse',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.TrainingEvents'),
        ),
    ]
