# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-28 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0024_auto_20250825_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registartion_type',
            field=models.PositiveSmallIntegerField(choices=[('', '-----'), (1, 'Subscribed College'), (2, 'Manual Registration'), (3, 'Self Subscribed'), (4, 'Self Registration')], default=1),
        ),
    ]
