# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-04-10 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20250825_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='is_swayam',
            field=models.BooleanField(default=False),
        ),
    ]
