# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_trainingevents_is_swayam'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='download_access',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
