# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-27 05:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_trainingevents_download_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingevents',
            name='event_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
    ]
