# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-02 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_auto_20260527_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='httpreferrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
