# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-27 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0027_auto_20260527_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILWAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilw_attendance_records', to='training.TrainingEvents')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_ilw_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilw_attendance_records', to='training.Participant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ilwattendance',
            unique_together=set([('event', 'participant')]),
        ),
    ]
