# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_auto_20260527_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevents',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
