# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-05 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_trainingevents_tdate'),
        ('training', '0028_auto_20260602_1203'),
    ]

    operations = [
    ]
