# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-05 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_merge_20260605_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
