# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-29 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0034_tutorialresource_is_on_youtube'),
        ('training', '0031_participant_apaar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilwfossmdlcourses',
            name='level',
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                to='creation.Level',
            ),
        ),
        migrations.AddField(
            model_name='trainingevents',
            name='level',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='creation.Level',
            ),
        ),
    ]
