# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-07-02 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0034_tutorialresource_is_on_youtube'),
        ('training', '0032_auto_20260629_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ILWCourseFossLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.ILWCourse')),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.FossCategory')),
                ('level', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='creation.Level')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingevents',
            name='level',
        ),
        migrations.AlterUniqueTogether(
            name='ilwcoursefosslevel',
            unique_together=set([('course', 'foss', 'level')]),
        ),
    ]
