# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-08-20 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20260128_1441'),
        ('training', '0033_auto_20260702_1318'),
    ]

    operations = [
    ]
