# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-08-22 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_merge_20260820_1542'),
        ('training', '0032_auto_20260731_1028'),
    ]

    operations = [
    ]
