# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-09-16 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_merge_20260822_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='added_by',
        ),
    ]
